port: 2468                              # 服务 HTTP 协议端口
mode: "std"                             # 默认为 std 标准库，另外可以设置 mmap 模式（本功能待完善）
path: "/tmp/wiredkv"                    # 数据库文件存储目录
auth: "Are we wide open to the world?"  # 访问 HTTP 协议的秘密
# WiredKV 在运行时程序产生的日志存储文件
logpath: "/tmp/wiredkv/out.log"    
debug: false        # 是否开启 debug 模式
region:             # 数据区
    enable: true    # 是否开启数据压缩功能
    second: 18000   # 默认垃圾回收器执行周期单位为秒
    threshold: 3    # 默认个数据文件大小，单位 GB
encryptor:          # 是否开启静态数据加密功能
    enable: false
    secret: "your-static-data-secret"
compressor:         # 是否开启静态数据压缩功能
    enable: false
allowip:           # 白名单 IP 列表
    - 192.168.31.1
    - 192.168.31.2